version: "3.8"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    environment:
       - CSVBORDER=Orange
    volumes:
      - ./inputFile:/csvserver/inputdata
